// Mocks generated by Mockito 5.4.4 from annotations
// in fudo_flutter/test/src/features/posts/domain/repositories/post_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fudo_flutter/src/features/posts/domain/entities/post_entity.dart'
    as _i2;
import 'package:fudo_flutter/src/features/posts/domain/repositories/post_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostEntity_0 extends _i1.SmartFake implements _i2.PostEntity {
  _FakePostEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PostEntity>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i4.Future<List<_i2.PostEntity>>.value(<_i2.PostEntity>[]),
      ) as _i4.Future<List<_i2.PostEntity>>);

  @override
  _i4.Future<_i2.PostEntity> createRandomPost(_i2.PostEntity? post) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRandomPost,
          [post],
        ),
        returnValue: _i4.Future<_i2.PostEntity>.value(_FakePostEntity_0(
          this,
          Invocation.method(
            #createRandomPost,
            [post],
          ),
        )),
      ) as _i4.Future<_i2.PostEntity>);
}
