name: fudo_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

# Local storage
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

# Navigation
  go_router: ^14.2.1
  go_router_builder: ^2.7.0

# Network
  dio: ^5.5.0+1
  connectivity_plus: ^2.3.8

# Others
  material_floating_search_bar_2: ^0.5.0
  package_info_plus: ^4.2.0
  mockito: ^5.4.4



dev_dependencies:
  flutter_test:
    sdk: flutter
    
# Build runner
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  
# Lints
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  test: ^1.25.2

flutter:
  uses-material-design: true

  # assets:
  #   # Add assets from the images directory to the application.
  #   - assets/images/ 
